<!-- Generated by scripts/nucleo-icons.mjs from Nucleo ui/chevron-down (outline, 12px). Regenerate; do not edit. -->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 12 12"
    fill="none"
    :width="size"
    :height="size"
    focusable="false">
    <polyline
      points="1.75 4.25 6 8.5 10.25 4.25"
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"></polyline>
  </svg>
</template>

<script setup lang="ts">
import type { NucleoIconProps } from "../../../utils/icons";

const { size = 12 } = defineProps<NucleoIconProps>();
</script>
