<!-- Generated by scripts/nucleo-icons.mjs from Nucleo ui/chevron-down (outline, 18px). Regenerate; do not edit. -->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    fill="none"
    :width="size"
    :height="size"
    focusable="false">
    <polyline
      points="15.25 6.5 9 12.75 2.75 6.5"
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"></polyline>
  </svg>
</template>

<script setup lang="ts">
import type { NucleoIconProps } from "../../../utils/icons";

const { size = 18 } = defineProps<NucleoIconProps>();
</script>
