<!-- Generated by scripts/nucleo-icons.mjs from Nucleo ui/chevron-up (outline, 12px). Regenerate; do not edit. -->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 12 12"
    fill="none"
    :width="size"
    :height="size"
    focusable="false">
    <polyline
      points="10.25 7.75 6 3.5 1.75 7.75"
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"></polyline>
  </svg>
</template>

<script setup lang="ts">
import type { NucleoIconProps } from "../../../utils/icons";

const { size = 12 } = defineProps<NucleoIconProps>();
</script>
