<!-- Generated by scripts/nucleo-icons.mjs from Nucleo ui/chevron-expand-y (outline, 18px). Regenerate; do not edit. -->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    fill="none"
    :width="size"
    :height="size"
    focusable="false">
    <polyline
      points="12.5 6.25 9 2.75 5.5 6.25"
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"></polyline>
    <polyline
      points="12.5 11.75 9 15.25 5.5 11.75"
      fill="none"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
      data-color="color-2"></polyline>
  </svg>
</template>

<script setup lang="ts">
import type { NucleoIconProps } from "../../../utils/icons";

const { size = 18 } = defineProps<NucleoIconProps>();
</script>
