<!-- Generated by scripts/nucleo-icons.mjs from Nucleo ui/sidebar-right (glyph-duo, 18px). Regenerate; do not edit. -->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    fill="none"
    :width="size"
    :height="size"
    focusable="false">
    <path
      :opacity="duoOpacity"
      d="M14.2501 2H3.75009C2.23131 2 1.00009 3.23122 1.00009 4.75V13.25C1.00009 14.7688 2.23131 16 3.75009 16H14.2501C15.7689 16 17.0001 14.7688 17.0001 13.25V4.75C17.0001 3.23122 15.7689 2 14.2501 2Z"
      fill="currentColor"
      data-color="color-2"></path>
    <path
      d="M11.0001 16H14.2501C15.7667 16 17.0001 14.7666 17.0001 13.25V4.75C17.0001 3.2334 15.7667 2 14.2501 2H11.0001V16Z"
      fill="currentColor"></path>
  </svg>
</template>

<script setup lang="ts">
import type { NucleoIconProps } from "../../../utils/icons";

const { size = 18, duoOpacity = 0.4 } = defineProps<NucleoIconProps>();
</script>
