<!-- Generated by scripts/nucleo-icons.mjs from Nucleo ui/square-dashed-2 (glyph, 18px). Regenerate; do not edit. -->
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 18 18"
    fill="none"
    :width="size"
    :height="size"
    focusable="false">
    <path
      d="m10.25,3.5h-2.5c-.4141,0-.75-.3359-.75-.75s.3359-.75.75-.75h2.5c.4141,0,.75.3359.75.75s-.3359.75-.75.75Z"
      fill="currentColor"
      stroke-width="0"
      data-color="color-2"></path>
    <path
      d="m10.25,16h-2.5c-.4141,0-.75-.3359-.75-.75s.3359-.75.75-.75h2.5c.4141,0,.75.3359.75.75s-.3359.75-.75.75Z"
      fill="currentColor"
      stroke-width="0"
      data-color="color-2"></path>
    <path
      d="m15.25,11c-.4141,0-.75-.3359-.75-.75v-2.5c0-.4141.3359-.75.75-.75s.75.3359.75.75v2.5c0,.4141-.3359.75-.75.75Z"
      fill="currentColor"
      stroke-width="0"
      data-color="color-2"></path>
    <path
      d="m2.75,11c-.4141,0-.75-.3359-.75-.75v-2.5c0-.4141.3359-.75.75-.75s.75.3359.75.75v2.5c0,.4141-.3359.75-.75.75Z"
      fill="currentColor"
      stroke-width="0"
      data-color="color-2"></path>
    <path
      d="m2.75,5.5c-.4141,0-.75-.3359-.75-.75v-1c0-.9648.7852-1.75,1.75-1.75h1c.4141,0,.75.3359.75.75s-.3359.75-.75.75h-1c-.1377,0-.25.1123-.25.25v1c0,.4141-.3359.75-.75.75Z"
      stroke-width="0"
      fill="currentColor"></path>
    <path
      d="m15.25,5.5c-.4141,0-.75-.3359-.75-.75v-1c0-.1377-.1123-.25-.25-.25h-1c-.4141,0-.75-.3359-.75-.75s.3359-.75.75-.75h1c.9648,0,1.75.7852,1.75,1.75v1c0,.4141-.3359.75-.75.75Z"
      stroke-width="0"
      fill="currentColor"></path>
    <path
      d="m14.25,16h-1c-.4141,0-.75-.3359-.75-.75s.3359-.75.75-.75h1c.1377,0,.25-.1123.25-.25v-1c0-.4141.3359-.75.75-.75s.75.3359.75.75v1c0,.9648-.7852,1.75-1.75,1.75Z"
      stroke-width="0"
      fill="currentColor"></path>
    <path
      d="m4.75,16h-1c-.9648,0-1.75-.7852-1.75-1.75v-1c0-.4141.3359-.75.75-.75s.75.3359.75.75v1c0,.1377.1123.25.25.25h1c.4141,0,.75.3359.75.75s-.3359.75-.75.75Z"
      stroke-width="0"
      fill="currentColor"></path>
  </svg>
</template>

<script setup lang="ts">
import type { NucleoIconProps } from "../../../utils/icons";

const { size = 18 } = defineProps<NucleoIconProps>();
</script>
